project:
  type: book

book:
  title: "Embrace the Majesty"
  author: "Subhojit Maji"
  date: "11/9/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - acheivements.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: vapor
#  pdf:
#    documentclass: scrreprt
#  epub:
#    cover-image: cover.png